const $=s=>document.querySelector(s);
let page=1,pages=1,lastMode='search',selected=null,relatedItems=[],currentRow=null;
let view={x:0,y:0,zoom:1,yaw:-0.45,pitch:0.22},modelData=null,modelFrameApi='',three=null,animationToken=0,modelPlaying=true;
const PAGE_SIZE=100;
async function api(path){const r=await fetch(path),j=await r.json();if(!r.ok||j.error)throw new Error(j.error||r.statusText);return j}
function status(t,bad=false){$('#status').textContent=t;$('#status').style.color=bad?'#ff8b8b':'#9bd1ff'}
function size(n){if(n===0)return'0 B';const u=['B','KiB','MiB','GiB'];let i=Math.min(3,Math.floor(Math.log(n)/Math.log(1024)));return(n/1024**i).toFixed(i?2:0)+' '+u[i]}
async function init(){try{const s=await api('/api/status');applyStatus(s);await search()}catch(e){status('加载失败：'+e.message,true)}}
function applyStatus(s){$('#gameDir').value=s.gameDir;$('#pack').innerHTML='<option value="">全部 JMP</option>'+s.packs.filter(p=>p.ok).map(p=>`<option>${p.name}</option>`).join('');$('#stats').textContent=`资源包：${s.validPackCount} / ${s.packCount}\n资源总数：${s.resourceCount.toLocaleString()}\n`+s.packs.filter(p=>p.warning||p.error).map(p=>`${p.name}：${p.warning||p.error}`).join('\n');status(`已加载 ${s.validPackCount} 个资源包，共 ${s.resourceCount.toLocaleString()} 项资源`)}
async function search(reset=true){if(reset)page=1;lastMode='search';const q=new URLSearchParams({q:$('#query').value,category:$('#category').value,pack:$('#pack').value,page,pageSize:PAGE_SIZE});try{status('正在搜索全部资源包…');render(await api('/api/search?'+q));status('搜索完成')}catch(e){status('搜索失败：'+e.message,true)}}
function renderRelated(){const start=(page-1)*PAGE_SIZE;render({items:relatedItems.slice(start,start+PAGE_SIZE),total:relatedItems.length,page,pageSize:PAGE_SIZE})}
async function related(){const hero=$('#hero').value.trim();if(!hero){status('请输入英雄编号',true);return}lastMode='related';page=1;try{status('正在关联模型、皮肤、贴图、特效和语音…');const d=await api('/api/related?hero='+encodeURIComponent(hero));relatedItems=d.items;renderRelated();$('#stats').textContent=`角色 ${d.hero} 关联资源：${d.total}\n`+Object.entries(d.counts).map(([k,v])=>`${k}：${v}`).join('\n');status(`关联搜索完成：角色 ${d.hero}，${d.total} 项`)}catch(e){status('关联搜索失败：'+e.message,true)}}
function render(d){pages=Math.max(1,Math.ceil(d.total/d.pageSize));page=d.page;$('#resultInfo').textContent=`${d.total.toLocaleString()} 项`;$('#pageInfo').textContent=`${page} / ${pages}`;$('#prev').disabled=page<=1;$('#next').disabled=page>=pages;$('#results').innerHTML=d.items.map(x=>`<tr data-id="${x.id}"><td>${x.category}</td><td title="${x.path}">${x.path}</td><td>${x.pack}</td><td>${size(x.rsize===4294967295?x.csize:x.rsize)}</td></tr>`).join('');document.querySelectorAll('#results tr').forEach(tr=>tr.onclick=()=>preview(tr.dataset.id,tr));$('.table-wrap').scrollTop=0}
function resetMedia(){const audio=$('#audio');audio.pause();audio.removeAttribute('src');audio.load();$('#image').removeAttribute('src');$('#live2d').src='about:blank';for(const x of ['image','model','modelBar','live2d','transformLayer','viewTools','bank','audio','tableView','report'])$('#'+x).hidden=true;$('#tableView').replaceChildren();$('#report').textContent='';modelData=null;modelFrameApi='';animationToken++;if(three){three.renderer.dispose();three=null}resetView()}
function resetView(){view={x:0,y:0,zoom:1,yaw:-0.45,pitch:0.22};applyTransform();if(three){three.controls.reset();drawModel()}else if(modelData)drawModel()}
function applyTransform(){if(!modelData)$('#transformLayer').style.transform=`translate(${view.x}px,${view.y}px) scale(${view.zoom})`;else $('#transformLayer').style.transform='none'}
async function preview(id,row){try{selected=id;currentRow=row;document.querySelectorAll('#results tr').forEach(x=>x.classList.toggle('selected',x===row));status('正在读取资源…');resetMedia();const d=await api('/api/preview?id='+encodeURIComponent(id));$('#empty').hidden=true;$('#preview').hidden=false;$('#title').textContent=d.name;$('#detail').textContent=`${d.path}\n${d.pack} #${d.index} · ${d.category} · ${size(d.size)} · MD5 ${d.md5}`;if(d.view==='image'){$('#transformLayer').hidden=false;$('#viewTools').hidden=false;$('#image').src='/api/raw?id='+encodeURIComponent(id);$('#image').hidden=false}else if(d.view==='audio'){$('#audio').src='/api/raw?id='+encodeURIComponent(id);$('#audio').hidden=false}else if(d.view==='bank'){const sel=$('#bankTrack');sel.innerHTML=d.tracks.map((t,i)=>`<option value="${i}">${i+1}. ${t.name} · ${t.codec} · ${t.rate}Hz · ${t.duration.toFixed(2)}s</option>`).join('');$('#bank').hidden=false;$('#bankPlay').onclick=async()=>{const button=$('#bankPlay');button.disabled=true;button.textContent='正在解码…';try{$('#audio').src='/api/audio-track?id='+encodeURIComponent(id)+'&track='+sel.value;$('#audio').hidden=false;await $('#audio').play();button.textContent='重新播放'}catch(e){status('音轨播放失败：'+e.message,true);button.textContent='播放所选音轨'}finally{button.disabled=false}}}else if(d.view==='model'){$('#transformLayer').hidden=false;$('#viewTools').hidden=false;modelData=d.model;modelFrameApi=d.modelFrameApi;$('#model').hidden=false;const as=$('#modelAction');as.innerHTML=(modelData.actions?.length?modelData.actions:[{name:'静态姿势'}]).map((a,i)=>`<option value="${i}">${a.name}</option>`).join('');$('#modelBar').hidden=false;modelPlaying=true;$('#modelPlay').textContent='暂停动作';initModel3D()}else if(d.view==='live2d'){const v=await api(d.live2dApi);$('#live2d').src=v.url;$('#live2d').hidden=false}else if(d.view==='table'){const cols=d.columns,rows=d.rows;$('#tableView').innerHTML=`<div>共 ${d.rowCount} 行，当前显示 ${rows.length} 行</div><table><thead><tr>${cols.map(c=>`<th>${c}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(v=>`<td>${v??''}</td>`).join('')}</tr>`).join('')}</tbody></table>`;$('#tableView').hidden=false}else{$('#report').textContent=d.report||'没有可显示的信息';$('#report').hidden=false}status('预览已加载')}catch(e){resetMedia();$('#report').textContent='预览失败：'+e.message;$('#report').hidden=false;status('预览失败：'+e.message,true)}}
function selectRelative(delta){const rows=[...document.querySelectorAll('#results tr')];let i=currentRow?rows.indexOf(currentRow):-1;i=Math.max(0,Math.min(rows.length-1,i+delta));if(rows[i]){rows[i].click();rows[i].scrollIntoView({block:'nearest'})}}
function move(dx,dy){if(modelData&&three){const offset=three.camera.position.clone().sub(three.controls.target);const q=new THREE.Quaternion().setFromEuler(new THREE.Euler(dy*.006,dx*.006,0,'YXZ'));offset.applyQuaternion(q);three.camera.position.copy(three.controls.target).add(offset);drawModel()}else{view.x+=dx;view.y+=dy;applyTransform()}}
function zoom(k){view.zoom=Math.max(.15,Math.min(8,view.zoom*k));if(modelData&&three){three.camera.position.sub(three.controls.target).multiplyScalar(1/k).add(three.controls.target);drawModel()}else applyTransform()}
function drawModel(){if(three){three.controls.update();three.renderer.render(three.scene,three.camera)}}
function initModel3D(){
 const canvas=$('#model'),scene=new THREE.Scene();scene.background=new THREE.Color(0x0c1119);
 const camera=new THREE.PerspectiveCamera(42,1,.01,100000),renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:false});renderer.setPixelRatio(devicePixelRatio||1);renderer.outputEncoding=THREE.sRGBEncoding;
 const controls=new THREE.OrbitControls(camera,canvas);controls.enableDamping=true;controls.dampingFactor=.08;
 const ambient=new THREE.AmbientLight(0xffffff,1.25);scene.add(ambient);const light=new THREE.DirectionalLight(0xffffff,.65);light.position.set(.35,.6,.75);camera.add(light);scene.add(camera);
 const group=new THREE.Group(),meshes=[];group.rotation.x=-Math.PI/2;scene.add(group);const loader=new THREE.TextureLoader();
 for(const m of modelData.meshes){const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(m.positions,3));if(m.normals?.length===m.positions.length)g.setAttribute('normal',new THREE.Float32BufferAttribute(m.normals,3));else g.computeVertexNormals();if(m.uvs?.length)g.setAttribute('uv',new THREE.Float32BufferAttribute(m.uvs,2));g.setIndex(m.indices);const md=modelData.materials[m.materialId]||{},rid=modelData.textureIds?.[md.texture];let mat;if(rid){const tex=loader.load('/api/raw?id='+encodeURIComponent(rid),drawModel);tex.encoding=THREE.sRGBEncoding;tex.wrapS=tex.wrapT=THREE.RepeatWrapping;tex.flipY=false;mat=new THREE.MeshLambertMaterial({map:tex,transparent:true,alphaTest:.42,side:THREE.DoubleSide})}else mat=new THREE.MeshLambertMaterial({color:0xc7d7ed,side:THREE.DoubleSide});const mesh=new THREE.Mesh(g,mat);mesh.name=m.name;mesh.userData.sourceIndex=m.sourceIndex;group.add(mesh);meshes.push(mesh)}
 const axes=[[],[],[]];for(const m of modelData.meshes)for(let i=0;i<m.positions.length;i+=3){axes[0].push(m.positions[i]);axes[1].push(m.positions[i+2]);axes[2].push(-m.positions[i+1])}for(const a of axes)a.sort((x,y)=>x-y);const q=(a,p)=>a[Math.max(0,Math.min(a.length-1,Math.floor((a.length-1)*p)))],lo=new THREE.Vector3(q(axes[0],.02),q(axes[1],.02),q(axes[2],.02)),hi=new THREE.Vector3(q(axes[0],.98),q(axes[1],.98),q(axes[2],.98)),box=new THREE.Box3(lo,hi),center=box.getCenter(new THREE.Vector3()),sphere=box.getBoundingSphere(new THREE.Sphere());controls.target.copy(center);camera.position.set(center.x,center.y,center.z+sphere.radius*2.6);camera.near=Math.max(.001,sphere.radius/1000);camera.far=Math.max(100,sphere.radius*30);camera.updateProjectionMatrix();
 controls.saveState();three={scene,camera,renderer,controls,group,meshes,ambient,light};applyBrightness();resizeModel();const token=++animationToken;animateModel(token);drawModel()
}
function resizeModel(){if(!three)return;const c=$('#model'),r=c.getBoundingClientRect();three.renderer.setSize(Math.max(1,r.width),Math.max(1,r.height),false);three.camera.aspect=Math.max(.1,r.width/Math.max(1,r.height));three.camera.updateProjectionMatrix();drawModel()}
async function animateModel(token){let last=0;while(three&&token===animationToken){const now=performance.now();if(modelPlaying&&modelData.actions?.length&&now-last>80){last=now;try{const frame=await api(modelFrameApi+'&action='+$('#modelAction').value+'&time='+(modelPlaying?now/1000:0));if(!three||token!==animationToken)break;for(const mesh of three.meshes){const f=frame.meshes[mesh.userData.sourceIndex];if(!f)continue;mesh.visible=f.visible;const a=mesh.geometry.attributes.position;if(a.array.length===f.positions.length){a.array.set(f.positions);a.needsUpdate=true;mesh.geometry.computeVertexNormals()}}}catch(e){status('模型动作预览失败：'+e.message,true)}}drawModel();await new Promise(requestAnimationFrame)}}
function applyBrightness(){const value=Number($('#modelBrightness').value)/100;$('#brightnessValue').textContent=Math.round(value*100)+'%';if(three){three.ambient.intensity=1.25*value;three.light.intensity=.65*value;drawModel()}}
$('#searchBtn').onclick=()=>search();$('#query').onkeydown=e=>{if(e.key==='Enter')search()};$('#category').onchange=()=>search();$('#pack').onchange=()=>search();$('#relatedBtn').onclick=related;$('#hero').onkeydown=e=>{if(e.key==='Enter')related()};$('#prev').onclick=()=>{if(page>1){page--;lastMode==='related'?renderRelated():search(false)}};$('#next').onclick=()=>{if(page<pages){page++;lastMode==='related'?renderRelated():search(false)}};
$('#modelPlay').onclick=()=>{modelPlaying=!modelPlaying;$('#modelPlay').textContent=modelPlaying?'暂停动作':'播放动作'};$('#modelAction').onchange=()=>{animationToken++;if(three)animateModel(++animationToken)};$('#itemUp').onclick=()=>selectRelative(-1);$('#itemDown').onclick=()=>selectRelative(1);$('#moveLeft').onclick=()=>move(-24,0);$('#moveRight').onclick=()=>move(24,0);$('#moveUp').onclick=()=>move(0,-24);$('#moveDown').onclick=()=>move(0,24);$('#zoomIn').onclick=()=>zoom(1.2);$('#zoomOut').onclick=()=>zoom(1/1.2);$('#viewReset').onclick=resetView;
$('#modelBrightness').oninput=applyBrightness;
window.addEventListener('keydown',e=>{if(/INPUT|SELECT|TEXTAREA/.test(e.target.tagName))return;if(e.key==='ArrowUp'){e.preventDefault();selectRelative(-1)}else if(e.key==='ArrowDown'){e.preventDefault();selectRelative(1)}else if(!$('#viewTools').hidden&&e.key==='ArrowLeft'){e.preventDefault();move(-24,0)}else if(!$('#viewTools').hidden&&e.key==='ArrowRight'){e.preventDefault();move(24,0)}else if(!$('#viewTools').hidden&&(e.key==='+'||e.key==='='))zoom(1.2);else if(!$('#viewTools').hidden&&e.key==='-')zoom(1/1.2)});
$('#visual').addEventListener('wheel',e=>{if(!$('#image').hidden||!$('#model').hidden){e.preventDefault();zoom(e.deltaY<0?1.12:1/1.12)}},{passive:false});window.addEventListener('resize',resizeModel);
$('#choose').onclick=async()=>{try{applyStatus(await api('/api/select-game-dir'));await search()}catch(e){status(e.message,true)}};$('#reload').onclick=async()=>{try{applyStatus(await api('/api/reload?gameDir='+encodeURIComponent($('#gameDir').value)));await search()}catch(e){status(e.message,true)}};init();
